#

name: Secrets scanning

on:
    workflow_call:

jobs:
    scan-secrets:
        runs-on: ubuntu-latest
        steps:
        -   name: Code Checkout
            uses: actions/checkout@v7
            with:
                fetch-depth: 0

        -   name: Github scanner
            uses: gitleaks/gitleaks-action@v3